{% set name = "dvclive" %}
{% set version = "3.43.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dvclive-{{ version }}.tar.gz
  sha256: 108d12c14f76d6137798ed6ed9b846a1989cce7c56ee098d27557c60a13b37bc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.9
    - setuptools_scm >=6.3.1
  run:
    - dvc >=3.48.4
    - pynvml

test:
  imports:
    - dvclive
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://dvc.org/doc/dvclive
  summary: Metric logger for ML projects.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - daavoo
    - efiop
    - shcheklein
