{% set name = "dvclive" %}
{% set version = "2.15.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dvclive-{{ version }}.tar.gz
  sha256: c3b2ca6b8268459f0e88958f8d1facaeefbfa836911bac3d2f972f842519007d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools_scm >=6.3.1
  run:
    - dvc >2.45.1
    - funcy
    - ruamel.yaml >=0.15.0
    - python >=3.8

test:
  imports:
    - dvclive
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://dvc.org/doc/dvclive
  summary: Metric logger for ML projects.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - daavoo
    - efiop
    - shcheklein
